/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.programacion.views.jfontchooser.panels;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author WTorres
 */
public class PnlOpen extends javax.swing.JPanel {

    /**
     * Creates new form PnlOpen
     */
    public PnlOpen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tfDirectoryPath = new javax.swing.JTextField();
        btnOpen = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaViewsFile = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(116, 199));
        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(tfDirectoryPath, gridBagConstraints);

        btnOpen.setText("...");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(btnOpen, gridBagConstraints);

        txtaViewsFile.setColumns(20);
        txtaViewsFile.setLineWrap(true);
        txtaViewsFile.setRows(5);
        txtaViewsFile.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(txtaViewsFile);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jScrollPane2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
              JFileChooser fc = new JFileChooser();
            FileNameExtensionFilter f = new FileNameExtensionFilter("*.TXT","txt" );
            fc.setFileFilter(f);
            int seleccion = fc.showOpenDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION){

                File fichero = fc.getSelectedFile();
                this.tfDirectoryPath.setText(fichero.getAbsolutePath());

                try (FileReader fr = new FileReader(fichero)){
                    String cadena = " ";
                    int valor = fr.read();
                    while (valor != -1){
                        cadena = cadena + (char) valor;
                        valor = fr.read();
                    }
                    this.txtaViewsFile.setText(cadena);
                }
                catch (IOException e1){
                    e1.printStackTrace();
                }

        }

    }//GEN-LAST:event_btnOpenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpen;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tfDirectoryPath;
    private javax.swing.JTextArea txtaViewsFile;
    // End of variables declaration//GEN-END:variables
}
